export const GROUP_TYPE_SHORTIES_IF_ACCEPTED_GROUP = ['AA'];
export const GROUP_TYPE_SHORTIES_WITH_ACCEPTANCE_FIELD = ['AB'];
export const GROUP_TYPE_SHORTIES_AUTO_ACCEPTED = ['STAND'];
export const GROUP_TYPE_SHORTIES_WITH_ACCEPT = [
    ...GROUP_TYPE_SHORTIES_WITH_ACCEPTANCE_FIELD,
    ...GROUP_TYPE_SHORTIES_AUTO_ACCEPTED,
];
export const GROUP_TYPE_SHORTIES = [...GROUP_TYPE_SHORTIES_IF_ACCEPTED_GROUP, ...GROUP_TYPE_SHORTIES_WITH_ACCEPT];

export const STARTPAGE_CATEGORY_ID = 17;
export const STARTPAGE_WIKIPAGE_ID = '_UI_.Startseite.begruessung';
export const STARTPAGE_FOOTER_WIKIPAGE_ID = '_UI_.Startseite.kontakt';

export const FIFTEEN_MINUTES = 15 * 60 * 1000;
